# name: Build Thesis PDF

# on:
#   push:
#     paths:
#       - 'thesis/*'
#     branches:
#       - main

# jobs:
#   build_latex:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Compile LaTeX
#         uses: xu-cheng/latex-action@v3
#         with:
#           working_directory: thesis
#           root_file: main.tex
#           command: make

#       - name: Upload PDF Artifact
#         uses: actions/upload-artifact@v4
#         with:
#           name: thesis
#           path: thesis/build/main.pdf            
